Repository rust-lang/rustfmt, pull requests merged in 2020-11, with the labels that each got.

#4482 Fixed comment dropped between & and type issue
  src/formatting/types.rs
  tests/source/issue-4245.rs
  tests/target/issue-4245.rs
Labels: hacktoberfest-accepted

#4445 Option to create groups for std, external crates, and other imports
  Configurations.md
  src/config.rs
  src/config/options.rs
  src/formatting/reorder.rs
  tests/source/configs/group_imports/StdExternalCrate-merge_imports.rs
  tests/source/configs/group_imports/StdExternalCrate-nested.rs
  tests/source/configs/group_imports/StdExternalCrate-no_reorder.rs
  tests/source/configs/group_imports/StdExternalCrate.rs
  tests/target/configs/group_imports/StdExternalCrate-merge_imports.rs
  tests/target/configs/group_imports/StdExternalCrate-nested.rs
  tests/target/configs/group_imports/StdExternalCrate-no_reorder.rs
  tests/target/configs/group_imports/StdExternalCrate.rs
Labels: hacktoberfest-accepted, pr-ready-to-merge

#4531 [Backport] Option to create groups for imports
  Configurations.md
  src/config/mod.rs
  src/config/options.rs
  src/reorder.rs
  tests/source/configs/group_imports/StdExternalCrate-merge_imports.rs
  tests/source/configs/group_imports/StdExternalCrate-nested.rs
  tests/source/configs/group_imports/StdExternalCrate-no_reorder.rs
  tests/source/configs/group_imports/StdExternalCrate.rs
  tests/target/configs/group_imports/StdExternalCrate-merge_imports.rs
  tests/target/configs/group_imports/StdExternalCrate-nested.rs
  tests/target/configs/group_imports/StdExternalCrate-no_reorder.rs
  tests/target/configs/group_imports/StdExternalCrate.rs
Labels: pr-not-reviewed
