Repository rust-lang/rustfmt, pull requests merged in 2021-03, with the labels that each got.

#4661 Comments between assignment (without let) lhs and rhs handling
  src/formatting/expr.rs
  tests/source/lhs-to-rhs-between-comments/assignment.rs
  tests/target/lhs-to-rhs-between-comments/assignment.rs
Labels: pr-waiting-on-author

#4720 Issue 4668
  src/formatting/comment.rs
  tests/source/comment2.rs
  tests/source/comment4.rs
  tests/source/issue-4668.rs
  tests/target/comment2.rs
  tests/target/comment4.rs
  tests/target/issue-4668.rs
Labels: pr-waiting-on-author

#4737 Dedup `imports_granularity = "Item"`
  src/formatting/imports.rs
  tests/source/imports/imports-impl-only-use.rs
  tests/source/imports/imports-reorder-lines-and-items.rs
  tests/source/imports/imports-reorder-lines.rs
  tests/source/imports/imports-reorder.rs
  tests/source/imports/imports.rs
  tests/source/imports/imports_2015_edition.rs
  tests/source/imports/imports_block_indent.rs
  tests/source/imports/imports_granularity_crate.rs
  tests/source/imports/imports_granularity_default-with-dups.rs
  tests/source/imports/imports_granularity_item-with-dups-StdExternalCrate-no-reorder.rs
  tests/source/imports/imports_granularity_item-with-dups.rs
  tests/source/imports/imports_granularity_item.rs
  tests/source/imports/imports_granularity_module.rs
  tests/source/imports/imports_raw_identifiers.rs
  tests/target/imports/import-fencepost-length.rs
  tests/target/imports/imports-impl-only-use.rs
  tests/target/imports/imports-reorder-lines-and-items.rs
  tests/target/imports/imports-reorder-lines.rs
  tests/target/imports/imports-reorder.rs
  tests/target/imports/imports.rs
  tests/target/imports/imports_2015_edition.rs
  tests/target/imports/imports_2021_edition.rs
  tests/target/imports/imports_block_indent.rs
  tests/target/imports/imports_granularity_crate.rs
  tests/target/imports/imports_granularity_default-with-dups.rs
  tests/target/imports/imports_granularity_item-with-dups-StdExternalCrate-no-reorder.rs
  tests/target/imports/imports_granularity_item-with-dups.rs
  tests/target/imports/imports_granularity_item.rs
  tests/target/imports/imports_granularity_module.rs
  tests/target/imports/imports_raw_identifiers.rs
Labels: pr-waiting-on-author

#4759 Fix issue with extra semicolon when import comment precedes semicolon
  src/formatting/lists.rs
  tests/source/imports/imports_granularity_crate-with-comments.rs
  tests/source/imports/imports_granularity_default-with-comments.rs
  tests/source/imports/imports_granularity_item-with-comments.rs
  tests/source/imports/imports_granularity_module-with-comments.rs
  tests/target/imports/imports_granularity_crate-with-comments.rs
  tests/target/imports/imports_granularity_default-with-comments.rs
  tests/target/imports/imports_granularity_item-with-comments.rs
  tests/target/imports/imports_granularity_module-with-comments.rs
Labels: pr-not-reviewed

#4680 Implement `One` option for imports_granularity
  Configurations.md
  src/config/options.rs
  src/formatting/imports.rs
  src/formatting/reorder.rs
  tests/source/imports_granularity_one.rs
  tests/target/imports_granularity_one.rs
Labels: pr-waiting-on-author

#4766 Fix comment removing issue of unit types in struct fields
  src/formatting/overflow.rs
  tests/source/issue-4749.rs
  tests/target/issue-4749.rs
Labels: pr-ready-to-merge
