Repository rust-lang/rustfmt, pull requests merged in 2021-11, with the labels that each got.

#5060 Put empty trait braces on same line if possible
  src/items.rs
  tests/source/empty-item-single-line-false.rs
  tests/source/item-brace-style-always-next-line.rs
  tests/target/empty-item-single-line-false.rs
  tests/target/item-brace-style-always-next-line.rs
Labels: 2x-port:pending

#5084 Add a few missing tracking issues in Configurations.md
  Configurations.md
Labels: pr-not-reviewed

#5110 Minor readme tweak
  README.md
Labels: documentation

#5104 Add more tests for comments in lists
  tests/source/comments-in-lists/wrap-comments-not-normalized.rs
  tests/source/comments-in-lists/wrap-comments-true.rs
  tests/target/comments-in-lists/format-doc-comments.rs
  tests/target/comments-in-lists/wrap-comments-false.rs
  tests/target/comments-in-lists/wrap-comments-not-normalized.rs
  tests/target/comments-in-lists/wrap-comments-true.rs
Labels: pr-waiting-on-author
