Repository rust-lang/rustfmt, pull requests merged in 2021-09, with the labels that each got.

#4903 Feature: upper- or lowercase hexadecimal literals
  Configurations.md
  src/config/mod.rs
  src/config/options.rs
  src/expr.rs
  tests/source/hex_literal_lower.rs
  tests/source/hex_literal_upper.rs
  tests/target/hex_literal_lower.rs
  tests/target/hex_literal_preserve.rs
  tests/target/hex_literal_upper.rs
Labels: pr-waiting-on-author

#4945 rustfmt doc code blocks with multiple comma-separated attributes
  src/comment.rs
  tests/source/issue-3158.rs
  tests/target/issue-3158.rs
Labels: pr-ready-to-merge

#4999 Add tests for binop_separator = Back
  tests/source/binop-separator-back/bitwise.rs
  tests/source/binop-separator-back/comp.rs
  tests/source/binop-separator-back/logic.rs
  tests/source/binop-separator-back/math.rs
  tests/source/binop-separator-back/patterns.rs
  tests/source/binop-separator-back/range.rs
  tests/target/binop-separator-back/bitwise.rs
  tests/target/binop-separator-back/comp.rs
  tests/target/binop-separator-back/logic.rs
  tests/target/binop-separator-back/math.rs
  tests/target/binop-separator-back/patterns.rs
  tests/target/binop-separator-back/range.rs
Labels: 2x-port:pending
