Repository rust-lang/rustfmt, pull requests merged in 2022-07, with the labels that each got.

#5379 config_type: add unstable_variant attribute
  Cargo.lock
  Cargo.toml
  config_proc_macro/Cargo.lock
  config_proc_macro/Cargo.toml
  config_proc_macro/src/attrs.rs
  config_proc_macro/src/item_enum.rs
  config_proc_macro/tests/smoke.rs
  src/config/config_type.rs
  src/config/mod.rs
Labels: release-notes

#5347 feat: add skip_macro_invocations option
  Configurations.md
  src/config/config_type.rs
  src/config/macro_names.rs
  src/config/mod.rs
  src/skip.rs
  src/test/configuration_snippet.rs
  src/visitor.rs
  tests/source/skip_macro_invocations/all.rs
  tests/source/skip_macro_invocations/all_and_name.rs
  tests/source/skip_macro_invocations/empty.rs
  tests/source/skip_macro_invocations/name.rs
  tests/source/skip_macro_invocations/name_unknown.rs
  tests/source/skip_macro_invocations/names.rs
  tests/source/skip_macro_invocations/path_qualified_invocation_mismatch.rs
  tests/source/skip_macro_invocations/path_qualified_match.rs
  tests/source/skip_macro_invocations/path_qualified_name_mismatch.rs
  tests/source/skip_macro_invocations/use_alias_examples.rs
  tests/target/skip_macro_invocations/all.rs
  tests/target/skip_macro_invocations/all_and_name.rs
  tests/target/skip_macro_invocations/empty.rs
  tests/target/skip_macro_invocations/name.rs
  tests/target/skip_macro_invocations/name_unknown.rs
  tests/target/skip_macro_invocations/names.rs
  tests/target/skip_macro_invocations/path_qualified_invocation_mismatch.rs
  tests/target/skip_macro_invocations/path_qualified_match.rs
  tests/target/skip_macro_invocations/path_qualified_name_mismatch.rs
  tests/target/skip_macro_invocations/use_alias_examples.rs
Labels: release-notes

#5387 Rename `fn_args_layout` -> `fn_params_layout`
  Configurations.md
  src/config/config_type.rs
  src/config/mod.rs
  src/items.rs
  tests/config/small_tabs.toml
  tests/source/configs/fn_params_layout/compressed.rs
  tests/source/configs/fn_params_layout/tall.rs
  tests/source/configs/fn_params_layout/vertical.rs
  tests/source/fn-custom-7.rs
  tests/source/fn-custom.rs
  tests/source/fn_args_layout-vertical.rs
  tests/target/configs/fn_params_layout/compressed.rs
  tests/target/configs/fn_params_layout/tall.rs
  tests/target/configs/fn_params_layout/vertical.rs
  tests/target/fn-custom-7.rs
  tests/target/fn-custom.rs
  tests/target/fn_args_layout-vertical.rs
  tests/target/issue-4791/issue_4928.rs
Labels: release-notes

#5449 Remove useless conditional compilation - 2
  src/test/mod.rs
Labels: pr-ready-to-merge

#5446 Fix/comments inside trait generics gets duplicated
  src/items.rs
  tests/target/issue-5358.rs
Labels: pr-ready-to-merge

#5470 Improvements: Adding tests for the issue-4643.
  tests/source/issue-4643.rs
  tests/target/issue-4643.rs
Labels: pr-not-reviewed

#5468 Add test for issue 3987
  tests/source/issue-3987/format_macro_bodies_true.rs
  tests/target/issue-3987/format_macro_bodies_false.rs
  tests/target/issue-3987/format_macro_bodies_true.rs
Labels: p-low, pr-not-reviewed
