Repository rust-lang/rustfmt, pull requests merged in 2022-08, with the labels that each got.

#5390 Backport PR #4730
  src/types.rs
  tests/source/issue-4689/one.rs
  tests/source/issue-4689/two.rs
  tests/target/issue-4689/one.rs
  tests/target/issue-4689/two.rs
Labels: pr-ready-to-merge

#5479 Add GitHub Action to test master rustfmt formatting vs a feature branch
  .github/workflows/check_diff.yml
  ci/check_diff.sh
Labels: pr-not-reviewed

#5505 Unicode comment align
  src/lists.rs
  tests/source/comments_unicode.rs
  tests/target/comments_unicode.rs
Labels: release-notes
