Repository rust-lang/rustfmt, pull requests merged in 2023-06, with the labels that each got.

#5780 Recover comments between attrs and generic param
  src/overflow.rs
  src/types.rs
  tests/target/doc-of-generic-item.rs
Labels: release-notes

#5756 Add release notes for merged PRs with `release-notes` label
  CHANGELOG.md
Labels: pr-not-reviewed

#5732 Prevent ICE when calling parse_attribute without an attribute
  src/parse/macros/cfg_if.rs
  tests/rustfmt/main.rs
  tests/target/issue_5729.rs
Labels: release-notes

#5687 Adjust enum variant spans to exclude any explicit discriminant
  src/items.rs
  tests/source/issue_5686.rs
  tests/target/issue_5686.rs
Labels: release-notes

#5682 Update dependencies `cargo_metadata`, `env_logger` and `toml`
  Cargo.lock
  Cargo.toml
  src/cargo-fmt/main.rs
  src/cargo-fmt/test/targets.rs
Labels: pr-not-reviewed

#5423 Handling of numbered markdown lists.
  src/comment.rs
  tests/source/itemized-blocks/no_wrap.rs
  tests/source/itemized-blocks/wrap.rs
  tests/target/itemized-blocks/no_wrap.rs
  tests/target/itemized-blocks/wrap.rs
Labels: p-low, release-notes
