Repository rust-lang/rustfmt, pull requests merged in 2023-08, with the labels that each got.

#5864 Update Unicode data to 15.0
  Cargo.lock
  Cargo.toml
  src/string.rs
Labels: release-notes

#5883 Improve formatting of empty macro_rules! definitions
  src/macros.rs
  tests/source/issue_5882.rs
  tests/target/issue_5882.rs
Labels: release-notes

#5677 Don't flatten blocks that have labels
  src/matches.rs
  tests/target/issue_5676.rs
Labels: release-notes

#5845 refactor ABI formatting
  src/items.rs
  src/types.rs
  src/utils.rs
  tests/target/extern-rust.rs
Labels: release-notes

#5867 Remove newlines in where clauses for v2
  src/items.rs
  tests/source/issue-5655/one.rs
  tests/source/issue-5655/two.rs
  tests/target/issue-5655/one.rs
  tests/target/issue-5655/two.rs
Labels: pr-not-reviewed

#5879 Prevent ICE when formatting item-only `vec!{}`
  src/macros.rs
  tests/source/issue_5735.rs
  tests/target/issue_5735.rs
Labels: pr-not-reviewed

#5889 Use `OR` operator in Cargo.toml `license` field
  Cargo.toml
  config_proc_macro/Cargo.toml
Labels: pr-not-reviewed

#5894 Fix link in CHANGELOG.md
  CHANGELOG.md
Labels: pr-not-reviewed

#5896 Fix typos in index.html
  docs/index.html
Labels: pr-not-reviewed

#5839 fix: reject leading `.`, `)` without prefix as item marker
  src/comment.rs
  tests/source/issue-5835.rs
  tests/target/issue-5835.rs
Labels: pr-waiting-on-author
