Repository rust-lang/rustfmt, pull requests merged in 2023-09, with the labels that each got.

#5902 Fix checking if newline is needed before `else` in let-else statement
  src/items.rs
  tests/source/let_else.rs
  tests/source/let_else_v2.rs
  tests/target/let_else.rs
  tests/target/let_else_v2.rs
Labels: pr-waiting-on-author

#5536 Fix #5533: Prefer light_rewrite_comment if it is not a doccomment
  src/comment.rs
  tests/target/issue-5568.rs
  tests/target/issue_5533.rs
  tests/target/issue_5907.rs
Labels: pr-ready-to-merge

#5908 feat(cargo): Style help like cargo nightly
  Cargo.lock
  Cargo.toml
  src/cargo-fmt/main.rs
Labels: pr-ready-to-merge, release-notes

#5913 Bugfix/comment duplication
  src/expr.rs
  tests/target/issue-5871.rs
Labels: release-notes
