Repository rust-lang/rustfmt, pull requests merged in 2024-11, with the labels that each got.

#6375 repair Ord for UseSegment
  src/imports.rs
  tests/source/issue-6333.rs
  tests/target/issue-6333-2024.rs
  tests/target/issue-6333.rs
Labels: pr-ready-to-merge, release-notes

#6398 Return Result from Shape methods
  src/attr.rs
  src/chains.rs
  src/closures.rs
  src/expr.rs
  src/imports.rs
  src/items.rs
  src/lists.rs
  src/macros.rs
  src/matches.rs
  src/overflow.rs
  src/pairs.rs
  src/patterns.rs
  src/reorder.rs
  src/rewrite.rs
  src/shape.rs
  src/stmt.rs
  src/types.rs
  src/vertical.rs
  src/visitor.rs
Labels: pr-waiting-on-author

#6404 Use preinterned `path` symbol
  src/modules/visitor.rs
Labels: pr-ready-to-merge
