Repository rust-lang/rustfmt, pull requests merged in 2024-08, with the labels that each got.

#6258 Print a deterministic length of commit hash in --version
  build.rs
Labels: pr-ready-to-merge

#6262 impl rewrite_result for Pat, TuplePatField
  src/expr.rs
  src/patterns.rs
  src/types.rs
Labels: pr-ready-to-merge, GSoC

#6261 update rewrite functions in imports.rs
  src/imports.rs
  src/reorder.rs
Labels: pr-not-reviewed, GSoC

#6272 Ensure that `fn config_path` returns canonicalized paths.
  src/config/mod.rs
  src/config/options.rs
Labels: pr-ready-to-merge, release-notes

#6270 update rewrite_chain to return RewriteResult
  src/chains.rs
  src/expr.rs
Labels: pr-not-reviewed, GSoC

#6271 update macro rewrite functions to return RewriteResult
  src/expr.rs
  src/items.rs
  src/macros.rs
  src/patterns.rs
  src/rewrite.rs
  src/types.rs
  src/visitor.rs
Labels: pr-not-reviewed, GSoC

#6292 Remove outdated comment from `mac.yml`
  .github/workflows/mac.yml
Labels: pr-not-reviewed
