Repository rust-lang/rustfmt, pull requests merged in 2024-03, with the labels that each got.

#6101 fix clap deprecations
  src/cargo-fmt/main.rs
  src/format-diff/main.rs
Labels: release-notes

#6085 Ensure space around binary exprs
  src/expr.rs
  tests/source/issue-6059/repro.rs
  tests/target/issue-6059/additional.rs
  tests/target/issue-6059/repro.rs
Labels: pr-waiting-on-author

#6092 Fix failure with `=>` in comment after match `=>`
  src/matches.rs
  tests/source/arrow_in_comments/arrow_in_single_comment.rs
  tests/source/arrow_in_comments/multiple_arrows.rs
  tests/target/arrow_in_comments/arrow_in_single_comment.rs
  tests/target/arrow_in_comments/multiple_arrows.rs
Labels: pr-follow-up-review-pending

#5847 Initial work on formatting headers
  src/header.rs
  src/lib.rs
  src/macros.rs
  tests/target/keywords.rs
Labels: pr-ready-to-merge, release-notes

#6112 Fix: ICE with expanded code #6105
  src/expr.rs
  tests/rustfmt/main.rs
  tests/target/issue-5885.rs
  tests/target/issue-6105.rs
Labels: release-notes
