Repository rust-lang/rustfmt, pull requests merged in 2024-01, with the labels that each got.

#6007 fix a couply of clippy findings
  build.rs
  src/bin/main.rs
  src/cargo-fmt/main.rs
  src/cargo-fmt/test/mod.rs
  src/comment.rs
  src/emitter/checkstyle.rs
  src/emitter/json.rs
  src/format-diff/main.rs
  src/lib.rs
  src/macros.rs
  src/source_file.rs
  src/test/mod.rs
Labels: pr-not-reviewed

#6000 5801 enum variant doc comments are wrapped before `comment_width`
  src/items.rs
  tests/config/issue-5801-v1.toml
  tests/config/issue-5801-v2.toml
  tests/source/issue-5801/attribute_unexpectedly_wraps_before_max_width.rs
  tests/source/issue-5801/comment_unexpectedly_wraps_before_max_width.rs
  tests/target/issue-5801/attribute_does_not_wrap_within_max_width.rs
  tests/target/issue-5801/attribute_unexpectedly_wraps_before_max_width.rs
  tests/target/issue-5801/comment_does_not_wrap_within_max_width.rs
  tests/target/issue-5801/comment_unexpectedly_wraps_before_max_width.rs
Labels: pr-waiting-on-author

#5993 Add config option `generated_marker_line_search_limit`
  Configurations.md
  src/config/mod.rs
  src/formatting.rs
  src/formatting/generated.rs
  tests/source/configs/format_generated_files/false_with_generated_marker_line_search_limit.rs
  tests/source/configs/format_generated_files/false_with_marker_out_scope_size.rs
  tests/source/configs/format_generated_files/false_with_zero_search_limit.rs
  tests/source/configs/format_generated_files/true_with_marker_in_scope_size.rs
  tests/source/configs/format_generated_files/true_with_marker_not_in_header.rs
  tests/target/configs/format_generated_files/false_with_generated_marker_line_search_limit.rs
  tests/target/configs/format_generated_files/false_with_marker_out_scope_size.rs
  tests/target/configs/format_generated_files/false_with_zero_search_limit.rs
  tests/target/configs/format_generated_files/true_with_marker_in_scope_size.rs
  tests/target/configs/format_generated_files/true_with_marker_not_in_header.rs
Labels: pr-follow-up-review-pending

#5971 Format diff line to be easily clickable
  src/emitter/diff.rs
Labels: release-notes

#5753 Spelling
  CHANGELOG.md
  Configurations.md
  Processes.md
  ci/check_diff.sh
  intellij.md
  src/comment.rs
  src/config/config_type.rs
  src/config/mod.rs
  src/config/options.rs
  src/imports.rs
  src/items.rs
  src/matches.rs
  src/overflow.rs
  src/parse/session.rs
  src/test/configuration_snippet.rs
  src/visitor.rs
Labels: pr-waiting-on-author

#5582 Fix for #3805 - wrap macro that starts with nested body blocks
  src/macros.rs
  tests/source/issue-3805.rs
  tests/target/issue-3805.rs
Labels: pr-ready-to-merge
