Repository rust-lang/rustfmt, pull requests merged in 2024-10, with the labels that each got.

#6361 Hint which style_edition to use instead of version
  Configurations.md
  src/config/config_type.rs
Labels: pr-ready-to-merge

#6362 Defer changes for zero argument functions until `style_edition=2027`
  src/config/options.rs
  src/items.rs
  tests/source/issue-3278/style_edition_2015.rs
  tests/source/issue-3278/style_edition_2024.rs
  tests/source/issue-3278/style_edition_2027.rs
  tests/source/long-fn-1/style_edition_2015.rs
  tests/source/long-fn-1/style_edition_2024.rs
  tests/source/long-fn-1/style_edition_2027.rs
  tests/target/issue-3278/style_edition_2015.rs
  tests/target/issue-3278/style_edition_2024.rs
  tests/target/issue-3278/style_edition_2027.rs
  tests/target/long-fn-1/style_edition_2015.rs
  tests/target/long-fn-1/style_edition_2024.rs
  tests/target/long-fn-1/style_edition_2027.rs
Labels: p-high, pr-not-reviewed, a-2024-edition

#6275 `compile_rustfmt` rewrite
  check_diff/Cargo.toml
  check_diff/src/lib.rs
  check_diff/src/main.rs
Labels: pr-ready-to-merge

#6372 Fix typos
  CHANGELOG.md
  src/test/parser.rs
  tests/source/enum.rs
  tests/source/no_arg_with_comment.rs
  tests/target/enum.rs
  tests/target/issue_4573.rs
  tests/target/no_arg_with_comment.rs
Labels: pr-not-reviewed
