Repository rust-lang/rustfmt, pull requests merged in 2024-07, with the labels that each got.

#6225 chore: fix link syntax
  CHANGELOG.md
Labels: pr-ready-to-merge

#6226 chore: remove duplicate word
  src/config/mod.rs
Labels: pr-not-reviewed

#6220 Impl rewrite_result for ast nodes in types.rs
  src/types.rs
Labels: pr-ready-to-merge, GSoC

#6232 Test do nothing with doc comment with code
  tests/rustfmt/main.rs
  tests/target/issue-6109.rs
Labels: pr-not-reviewed

#6231 add release date for v1.7.1 to the CHANGELOG
  CHANGELOG.md
Labels: pr-not-reviewed

#5937 Impl `StyleEditionDefault` trait for all configs
  src/config/config_type.rs
  src/config/mod.rs
  src/config/options.rs
  src/config/style_edition.rs
Labels: p-high, pr-not-reviewed, a-2024-edition

#6239 impl rewrite_result for ArmWrapper
  src/expr.rs
  src/matches.rs
Labels: pr-ready-to-merge, GSoC

#6244 modify ListItem to hold RewriteResult as the item field
  src/attr.rs
  src/closures.rs
  src/expr.rs
  src/imports.rs
  src/items.rs
  src/lists.rs
  src/macros.rs
  src/matches.rs
  src/overflow.rs
  src/patterns.rs
  src/reorder.rs
  src/rewrite.rs
  src/types.rs
  src/vertical.rs
Labels: pr-not-reviewed, GSoC

#6248 refactor rewrite_array, pair, tuple, call
  src/attr.rs
  src/chains.rs
  src/expr.rs
  src/items.rs
  src/macros.rs
  src/overflow.rs
  src/pairs.rs
  src/patterns.rs
  src/spanned.rs
  src/types.rs
Labels: pr-not-reviewed, GSoC

#6253 track configs set from cli flags
  src/bin/main.rs
  src/config/config_type.rs
  src/config/file_lines.rs
  src/config/mod.rs
Labels: pr-not-reviewed

#6254 add a few tests for style edition config defaults
  src/config/mod.rs
Labels: pr-not-reviewed
