Repository rust-lang/rustfmt, pull requests merged in 2024-09, with the labels that each got.

#6295 update rewrite_assignment to return RewriteResult
  src/expr.rs
  src/items.rs
  src/macros.rs
  src/types.rs
Labels: pr-waiting-on-author, GSoC

#6291 impl rewrite_result for ControlFlow, Stmt, update rewrite_index
  src/comment.rs
  src/expr.rs
  src/items.rs
  src/overflow.rs
  src/stmt.rs
  src/types.rs
Labels: pr-waiting-on-author, GSoC

#6307 Fix `test_editions_2015_2018_2021_identical`
  src/config/mod.rs
Labels: pr-not-reviewed

#6311 impl rewrite_result for ast::Expr
  src/expr.rs
  src/matches.rs
  src/stmt.rs
  src/types.rs
  src/utils.rs
Labels: pr-ready-to-merge, GSoC

#6317 Add missing backtick in comment
  src/config/mod.rs
Labels: pr-not-reviewed

#6319 ci: bump actions/checkout to v4
  .github/workflows/check_diff.yml
  .github/workflows/integration.yml
  .github/workflows/linux.yml
  .github/workflows/mac.yml
  .github/workflows/rustdoc_check.yml
  .github/workflows/upload-assets.yml
  .github/workflows/windows.yml
Labels: pr-ready-to-merge

#6320 subtree-push nightly-2024-09-10
  rust-toolchain
  src/attr.rs
  src/chains.rs
  src/closures.rs
  src/comment.rs
  src/expr.rs
  src/format-diff/main.rs
  src/formatting.rs
  src/git-rustfmt/main.rs
  src/items.rs
  src/lib.rs
  src/macros.rs
  src/matches.rs
  src/missed_spans.rs
  src/modules/visitor.rs
  src/overflow.rs
  src/test/mod.rs
  src/types.rs
  src/visitor.rs
  tests/target/raw-lifetimes.rs
  tests/target/unsafe_attributes.rs
Labels: pr-not-reviewed

#6208 remove unused tracing-attributes
  Cargo.lock
  Cargo.toml
Labels: pr-ready-to-merge, release-notes

#6237 config_proc_macro: reduce syn's features
  config_proc_macro/Cargo.toml
Labels: pr-ready-to-merge, release-notes

#6328 Non-panicking `fmt::Display` for `FileName`
  src/bin/main.rs
  src/config/file_lines.rs
  src/test/mod.rs
Labels: pr-not-reviewed

#6337 chore: prep v1.8.0 release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: pr-not-reviewed

#6336 Preallocate missmatches in `JsonEmitter::add_misformatted_file`
  src/emitter/json.rs
Labels: pr-ready-to-merge

#6324 Add style_edition 2027
  src/bin/main.rs
  src/config/options.rs
  src/config/style_edition.rs
Labels: release-notes
