Repository rust-lang/rustfmt, pull requests merged in 2025-02, with the labels that each got.

#6390 `check_diff` function rewrite
  check_diff/Cargo.lock
  check_diff/Cargo.toml
  check_diff/src/lib.rs
  check_diff/src/main.rs
  check_diff/tests/check_diff.rs
Labels: pr-ready-to-merge

#5834 Add option to control trailing zero in floating-point literals
  Configurations.md
  src/chains.rs
  src/config/mod.rs
  src/config/options.rs
  src/expr.rs
  tests/source/configs/float_literal_trailing_zero/always.rs
  tests/source/configs/float_literal_trailing_zero/if-no-postfix.rs
  tests/source/configs/float_literal_trailing_zero/never.rs
  tests/target/configs/float_literal_trailing_zero/always.rs
  tests/target/configs/float_literal_trailing_zero/if-no-postfix.rs
  tests/target/configs/float_literal_trailing_zero/never.rs
  tests/target/configs/float_literal_trailing_zero/preserve.rs
Labels: pr-ready-to-merge

#6066 feat: use `semver` to match required version
  Cargo.lock
  Cargo.toml
  Configurations.md
  src/config/mod.rs
Labels: pr-follow-up-review-pending

#6487 docs: pull latest version from tags instead of releases in docs page
  docs/index.html
Labels: pr-not-reviewed

#6486 docs: clarify the editions behavior and it's consequences on formatting
  Configurations.md
  README.md
Labels: pr-ready-to-merge
